services:

  database:
    container_name: postgresql
    image: postgres
    user: postgres
    command: 'postgres'
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookshop_db
